version: '3.7'
services:
    php:
        container_name: supermetrics_api_php
        build:
            context: .
            dockerfile: docker/dev/php/Dockerfile
        volumes:
            - '.:/app'

    nginx:
        image: nginx:stable-alpine
        container_name: supermetrics_api_php_nginx
        depends_on:
            - php
        volumes:
            - './public/:/app/public:ro'
            - './docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '${NGINX_PUBLIC_PORT}:80'
